### ISSUE TITLE
Some WHMCS settings prevent the Purchase event

### ISSUE THREAD

**Issue by raphael-borges** [websavers/WHMCS-Google-Tag-Manager#13] opened 2023-08-23 18:48 UTC
We have three “Auto Redirect on Checkout” possibilities: 
1. **Not automatically redirect and just show the order completed page** — The order completed page will display a message allowing the client to log in to the Client Area to pay the outstanding invoice.
2. **Select to automatically redirect the user to the invoice** — An invoice will display order details and a payment button.
3. **Select to automatically redirect the user to the gateway** — The payment gateway will display and request their payment details.

On the first, the events works, but the other 2 complete ignore the hook `ShoppingCartCheckoutCompletePage`. 

I resolve it using the comeback of the payment gateway, on the page `*/viewinvoice.php?id=17&paymentsuccess=true`. But only work if the theme has a custom page invoice that load the module. 

```
add_hook('ClientAreaPageViewInvoice', 1, function ($vars) {
  add_hook('ClientAreaFooterOutput', 1, function ($vars) {

    if (gtm_get_module_settings('gtm-enable-datalayer') == 'off') return '';

    $res_orders = localAPI('GetOrders', array('id' => $vars['invoiceid']));
    $order = $res_orders['orders']['order'][0];

    $currencyCode = $order['currencysuffix'];

    $currencyPrefix = $order['currencyprefix'];

    //if ( $_REQUEST['debug'] ) var_dump($order); ///DEBUG

    $itemsArray = array();
    foreach ($order['lineitems']['lineitem'] as $product) {
      $p_g_n = explode(' - ', $product['product']);
      if (count($p_g_n) == 1) {
        $category = '';
        $name = $product['product'];
      } else if (count($p_g_n) == 2) {
        $category = $p_g_n[0];
        $name = $p_g_n[1];
      }
      $itemsArray[] = array(
        'item_name'      => $name,
        'item_id'        => $product['relid'],
        'price'          => gtm_format_price($product['amount'], $currencyCode, $currencyPrefix),
        'item_brand'     => '',
        'item_category'  => $category,
        'quantity'       => 1
      );
    }

    $res_invoice = localAPI('GetInvoice', array('invoiceid' => $order['invoiceid']));
    $tax = (float)$res_invoice['tax'] + (float)$res_invoice['tax2'];

    $eventArray = array(
      'event' => 'purchase',
      'ecommerce' => array(
        'transaction_id'  => $order['id'],
        'affiliation'     => 'WHMCS Orderform',
        'value'           => $order['amount'], // Total transaction value (incl. tax and shipping)
        'tax'             => $tax,
        'shipping'        => '',
        'currency'        => $currencyCode,
        'coupon'          => $order['promocode'],
        'items'           => $itemsArray
      )
    );
    $amountPaid = $vars['amountPaid'];

    if (isset($_GET['paymentsuccess']) && $amountPaid > '0') {
      //It is paided
      return "<script id='GTM_DataLayer'>
      dataLayer.push(" . json_encode($eventArray) . ");  
      console.log('Pago');
      </script>";
    } else if (!isset($_GET['paymentsuccess']) && $amountPaid > '0') {
      // It is paided, but is not a payment confirm page
    } else if (isset($_GET['paymentsuccess']) && $amountPaid == '0') {
      // It is not paided, but is a payment confirm page (Probably waiting for the gateway to confirm the payment.)
      return "<script id='GTM_DataLayer'>
      dataLayer.push(" . json_encode($eventArray) . ");
      console.log('Esperando pagamento');
    </script>";
    } else {
      // It is not paided and is not a payment confirm page
    }
  });
});

```

Without a custom invoice template, I call the event on the button checkout click: 
```
document.addEventListener('DOMContentLoaded', function () {
  var checkoutButton = document.getElementById('checkout');

  if (checkoutButton) {
    checkoutButton.addEventListener('click', function (event) {

      console.log('Evento disparado antes do redirecionamento para o checkout.');
      dataLayer.push({ ecommerce: null });  // Clear the previous ecommerce object.
      dataLayer.push(" . json_encode($eventArray) . ");
    });
  }
});
```

I don't know if it is the better solution.

**Comment by jas8522** [comment] 2023-08-24 00:33
I can certainly see how (2) would be an issue (redirect to invoice), but we use (3) with PayPal and it's still registering those orders because PayPal uses the IPN URL to bring the purchaser back to the checkout complete page. I always just assumed that any externally processed payment system would have to do that as well, otherwise don't you break the purchaser's continuity to easily find their way back to their account?

Perhaps for (2) on the checkout page, we could attach the checkout complete event to the Complete Checkout button click, rather than doing so on the invoice. Granted we'd be capturing the checkout early - before payment is actually received.

**Comment by raphael-borges** [comment] 2023-08-24 13:08
> but we use (3) with PayPal and it's still registering those orders because PayPal uses the IPN URL to bring the purchaser back to the checkout complete page.

I am not using the IPN URL on the test serve, I need to see how it's going on production gateway. 

But in Brazil, we have some payments that never bring back to site. For example, the "boleto bancario", is a document with a bar code that you pay on your bank (like a 90s QR code). You are redirected to document to print or pay on the app bank, and payment take up to 3 days to be confirmed. I think the only way to confirm this is on the button click before the payment. 

Some client like to user bank transfer too, so you need to manually confirm this on admin.

**Comment by jas8522** [comment] 2023-08-25 20:11
@raphael-borges in those cases there's definitely no way I can think of to ensure it's captured *after* payment is received. 

If we capture it via JS when the complete order button is clicked, then payment is received via a gateway like PayPal with correctly configured IPN, or even just regular ol' credit card, then two purchase events will be triggered: one when the complete order button is clicked and one when they're directed to the order complete page.

Therefore it seems like the best option for this is: in the module settings provide an option that specifies something like "Rather than capture purchase event after payment is received, capture the event when the customer presses the complete order button on the checkout page, prior to confirmed payment."

When that option is checked the code would need to be added to use the JS purchase event trigger (you have something like that already that could be modified) and we'd have to not utilize the code under the ShoppingCartCheckoutCompletePage hook to prevent duplicate triggers.

This *would* solve both (2) and (3), so it seems like it should be a good solution, though I'm also open to other ideas.

This isn't something I have a need for, so I don't plan on adding it, but you're welcome to do so with a PR!

**Comment by jas8522** [comment] 2024-10-01 14:51
Closing this - if someone wants to try implementing these workarounds for custom checkout templates, I welcome the pull request!

**Closed as completed by jas8522** 2024-10-01 14:51 UTC
